import numpy as np
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances, manhattan_distances


netmf = np.load('NetMF/netmf_embedding.npy')
word2vec_80 = np.load('node2vec/src/embedding/80_word2vec_embedding.npy')
word2vec_900 = np.load('node2vec/src/embedding/900_word2vec_embedding.npy')
word2vec_1000 = np.load('node2vec/src/embedding/1000_word2vec_embedding.npy')
word2vec_1100 = np.load('node2vec/src/embedding/1100_word2vec_embedding.npy')
word2vec_1200 = np.load('node2vec/src/embedding/1200_word2vec_embedding.npy')
word2vec_1300 = np.load('node2vec/src/embedding/1300_word2vec_embedding.npy')
word2vec_1400 = np.load('node2vec/src/embedding/1400_word2vec_embedding.npy')

netmf = netmf.reshape(1,-1)
word2vec_80 = word2vec_80.reshape(1,-1)
word2vec_900 = word2vec_900.reshape(1,-1)
word2vec_1000 = word2vec_1000.reshape(1,-1)
word2vec_1100 = word2vec_1100.reshape(1,-1)
word2vec_1200 = word2vec_1200.reshape(1,-1)
word2vec_1300 = word2vec_1300.reshape(1,-1)
word2vec_1400 = word2vec_1400.reshape(1,-1)

print('Walk Length 80 cosine_similarty = ',cosine_similarity(netmf, word2vec_80))
print('Walk Length 80 Euclidean distance = ', euclidean_distances(netmf, word2vec_80))
print('Walk Length 80 Manhattan distance = ', manhattan_distances(netmf, word2vec_80))
print("---------------------------------------------------------------------")
print('Walk Length 900 cosine_similarty = ',cosine_similarity(netmf, word2vec_900))
print('Walk Length 900 Euclidean distance = ', euclidean_distances(netmf, word2vec_900))
print('Walk Length 900 Manhattan distance = ', manhattan_distances(netmf, word2vec_900))
print("---------------------------------------------------------------------")
print('Walk Length 1000 cosine_similarty = ',cosine_similarity(netmf, word2vec_1000))
print('Walk Length 1000 Euclidean distance = ', euclidean_distances(netmf, word2vec_1000))
print('Walk Length 1000 Manhattan distance = ', manhattan_distances(netmf, word2vec_1000))
print("---------------------------------------------------------------------")
print('Walk Length 1100 cosine_similarty = ',cosine_similarity(netmf, word2vec_1100))
print('Walk Length 1100 Euclidean distance = ', euclidean_distances(netmf, word2vec_1100))
print('Walk Length 1100 Manhattan distance = ', manhattan_distances(netmf, word2vec_1100))
print("---------------------------------------------------------------------")
print('Walk Length 1200 cosine_similarty = ',cosine_similarity(netmf, word2vec_1200))
print('Walk Length 1200 Euclidean distance = ', euclidean_distances(netmf, word2vec_1200))
print('Walk Length 1200 Manhattan distance = ', manhattan_distances(netmf, word2vec_1200))
print("---------------------------------------------------------------------")
print('Walk Length 1300 cosine_similarty = ',cosine_similarity(netmf, word2vec_1300))
print('Walk Length 1300 Euclidean distance = ', euclidean_distances(netmf, word2vec_1300))
print('Walk Length 1300 Manhattan distance = ', manhattan_distances(netmf, word2vec_1300))
print("---------------------------------------------------------------------")
print('Walk Length 1400 cosine_similarty = ',cosine_similarity(netmf, word2vec_1400))
print('Walk Length 1400 Euclidean distance = ', euclidean_distances(netmf, word2vec_1400))
print('Walk Length 1400 Manhattan distance = ', manhattan_distances(netmf, word2vec_1400))
print("---------------------------------------------------------------------")